const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {
  // Populando a tabela Usuario
  await prisma.usuario.createMany({
    data: [
      {
        nome: "João Silva",
        email: "joao@exemplo.com",
        funcao: "Analista",
        admin: true,
        usuario: "joao.silva",
        senha: "senha123", // senha123 criptografada
      },
      {
        nome: "Maria Souza",
        email: "maria@exemplo.com",
        funcao: "Assistente",
        admin: false,
        usuario: "maria.souza",
        senha: "senha123",
      },
      {
        nome: "Pedro Oliveira",
        email: "pedro@exemplo.com",
        funcao: "Gerente",
        admin: true,
        usuario: "pedro.oliveira",
        senha: "senha123",
      },
      {
        nome: "Ana Santos",
        email: "ana@exemplo.com",
        funcao: "Coordenadora",
        admin: false,
        usuario: "ana.santos",
        senha: "senha123",
      },
      {
        nome: "Lucas Lima",
        email: "lucas@exemplo.com",
        funcao: "Técnico",
        admin: false,
        usuario: "lucas.lima",
        senha: "senha123",
      },
      {
        nome: "Fernanda Rocha",
        email: "fernanda@exemplo.com",
        funcao: "Desenvolvedora",
        admin: true,
        usuario: "fernanda.rocha",
        senha: "senha123",
      },
      {
        nome: "Gustavo Costa",
        email: "gustavo@exemplo.com",
        funcao: "Analista",
        admin: false,
        usuario: "gustavo.costa",
        senha: "senha123",
      },
      {
        nome: "Camila Martins",
        email: "camila@exemplo.com",
        funcao: "Assistente",
        admin: false,
        usuario: "camila.martins",
        senha: "senha123",
      },
      {
        nome: "Ricardo Lopes",
        email: "ricardo@exemplo.com",
        funcao: "Supervisor",
        admin: true,
        usuario: "ricardo.lopes",
        senha: "senha123",
      },
      {
        nome: "Juliana Almeida",
        email: "juliana@exemplo.com",
        funcao: "Gerente",
        admin: false,
        usuario: "juliana.almeida",
        senha: "senha123",
      },
    ],
  });

  // Populando a tabela Produto com componentes eletrônicos
  await prisma.produto.createMany({
    data: [
      {
        nome: "Resistor 220 Ohm",
        numero_serie: "RES-220-001",
        fabricante: "EletroComp",
        descricao: "Resistor de precisão 1%",
        tipo_unitario: "Unidade",
        quantidade: 1000,
        andar: "1",
        sala: "101",
        armario: "A1",
      },
      {
        nome: "Capacitor Cerâmico 100nF",
        numero_serie: "CAP-100N-002",
        fabricante: "Eletronix",
        descricao: "Capacitor de cerâmica para circuitos AC/DC",
        tipo_unitario: "Unidade",
        quantidade: 500,
        andar: "1",
        sala: "102",
        armario: "A2",
      },
      {
        nome: "Transistor NPN BC547",
        numero_serie: "TR-BC547-003",
        fabricante: "SemiTek",
        descricao: "Transistor de uso geral",
        tipo_unitario: "Unidade",
        quantidade: 750,
        andar: "2",
        sala: "201",
        armario: "B1",
      },
      {
        nome: "Microcontrolador ATmega328P",
        numero_serie: "MC-ATMEGA-004",
        fabricante: "MicroChip",
        descricao: "Microcontrolador usado em Arduino",
        tipo_unitario: "Unidade",
        quantidade: 200,
        andar: "2",
        sala: "202",
        armario: "B2",
      },
      {
        nome: "Indutor 10uH",
        numero_serie: "IND-10U-005",
        fabricante: "MagComp",
        descricao: "Indutor de potência",
        tipo_unitario: "Unidade",
        quantidade: 300,
        andar: "3",
        sala: "301",
        armario: "C1",
      },
      {
        nome: "Sensor de Temperatura LM35",
        numero_serie: "SEN-LM35-006",
        fabricante: "SensTech",
        descricao: "Sensor de temperatura de precisão",
        tipo_unitario: "Unidade",
        quantidade: 150,
        andar: "3",
        sala: "302",
        armario: "C2",
      },
      {
        nome: "Oscilador Cristalino 16MHz",
        numero_serie: "OSC-16M-007",
        fabricante: "OscilComp",
        descricao: "Cristal oscilador para circuitos de relógio",
        tipo_unitario: "Unidade",
        quantidade: 100,
        andar: "4",
        sala: "401",
        armario: "D1",
      },
      {
        nome: "Amplificador LM358",
        numero_serie: "AMP-LM358-008",
        fabricante: "AudioTech",
        descricao: "Amplificador operacional dual",
        tipo_unitario: "Unidade",
        quantidade: 400,
        andar: "4",
        sala: "402",
        armario: "D2",
      },
      {
        nome: "Diodo Zener 5V1",
        numero_serie: "DIO-Z5V1-009",
        fabricante: "Diodix",
        descricao: "Diodo regulador de tensão 5V",
        tipo_unitario: "Unidade",
        quantidade: 600,
        andar: "5",
        sala: "501",
        armario: "E1",
      },
      {
        nome: "Relé de Potência 5V",
        numero_serie: "REL-5V-010",
        fabricante: "PowerRelays",
        descricao: "Relé de acionamento com bobina de 5V",
        tipo_unitario: "Unidade",
        quantidade: 250,
        andar: "5",
        sala: "502",
        armario: "E2",
      },
      {
        nome: "Placa Arduino Uno",
        numero_serie: "ARD-UNO-011",
        fabricante: "Arduino",
        descricao: "Placa de prototipagem com microcontrolador",
        tipo_unitario: "Unidade",
        quantidade: 75,
        andar: "2",
        sala: "204",
        armario: "C3",
      },
      {
        nome: "Display LCD 16x2",
        numero_serie: "LCD-16X2-012",
        fabricante: "DisplayWorks",
        descricao: "Tela LCD para exibição de informações",
        tipo_unitario: "Unidade",
        quantidade: 120,
        andar: "4",
        sala: "402",
        armario: "D4",
      },
      {
        nome: "Módulo Bluetooth HC-05",
        numero_serie: "BLT-HC05-013",
        fabricante: "ConnectTech",
        descricao: "Módulo Bluetooth para comunicação sem fio",
        tipo_unitario: "Unidade",
        quantidade: 200,
        andar: "2",
        sala: "207",
        armario: "A3",
      },
      {
        nome: "Motor DC 12V",
        numero_serie: "MOT-DC12-014",
        fabricante: "MotoTech",
        descricao: "Motor elétrico para projetos de automação",
        tipo_unitario: "Unidade",
        quantidade: 50,
        andar: "5",
        sala: "503",
        armario: "C2",
      },
      {
        nome: "Protoboard 830 pontos",
        numero_serie: "PRO-830-015",
        fabricante: "ProtoWorks",
        descricao: "Placa de prototipagem para montagem de circuitos",
        tipo_unitario: "Unidade",
        quantidade: 90,
        andar: "4",
        sala: "406",
        armario: "E1",
      },
      {
        nome: "Módulo WiFi ESP8266",
        numero_serie: "WIF-ESP8266-016",
        fabricante: "NetConnect",
        descricao: "Módulo de comunicação WiFi para IoT",
        tipo_unitario: "Unidade",
        quantidade: 180,
        andar: "3",
        sala: "302",
        armario: "D3",
      },
      {
        nome: "Fonte de Alimentação 5V 2A",
        numero_serie: "FON-5V2A-017",
        fabricante: "PowerTech",
        descricao: "Fonte regulada para projetos eletrônicos",
        tipo_unitario: "Unidade",
        quantidade: 60,
        andar: "1",
        sala: "105",
        armario: "B3",
      },
      {
        nome: "Sensor de Movimento PIR",
        numero_serie: "SEN-PIR-018",
        fabricante: "MotionTech",
        descricao: "Sensor de movimento para automação",
        tipo_unitario: "Unidade",
        quantidade: 85,
        andar: "3",
        sala: "303",
        armario: "C4",
      },
      {
        nome: "Bateria LiPo 3.7V 2000mAh",
        numero_serie: "BAT-LIPO-019",
        fabricante: "BatteryPower",
        descricao: "Bateria recarregável para dispositivos móveis",
        tipo_unitario: "Unidade",
        quantidade: 120,
        andar: "5",
        sala: "504",
        armario: "E3",
      },
      {
        nome: "Conjunto Jumpers 40 peças",
        numero_serie: "JMP-40-020",
        fabricante: "ConnectParts",
        descricao: "Cabos para conexão em protoboards",
        tipo_unitario: "Kit",
        quantidade: 40,
        andar: "1",
        sala: "103",
        armario: "A4",
      },
    ],
  });

  // Populando a tabela Cliente
  await prisma.cliente.createMany({
    data: [
      {
        razao_social_cliente: "TecnoSolution Ltda",
        CNPJ: "12345678000191",
        inscricao_estadual: "1234567891",
        endereco: "Av. Central, 123",
        bairro: "Centro",
        CEP: "12345000",
        municipio: "TecnoCity",
        UF: "TC",
        telefone: "(11) 1111-1111",
      },
      {
        razao_social_cliente: "EletronPlus SA",
        CNPJ: "12345678000192",
        inscricao_estadual: "1234567892",
        endereco: "Rua das Indústrias, 45",
        bairro: "Industrial",
        CEP: "23456000",
        municipio: "EletronTown",
        UF: "ET",
        telefone: "(21) 2222-2222",
      },
      {
        razao_social_cliente: "MicroComp Comércio",
        CNPJ: "12345678000193",
        inscricao_estadual: "1234567893",
        endereco: "Av. Digital, 98",
        bairro: "Comércio",
        CEP: "34567000",
        municipio: "MicroCity",
        UF: "MC",
        telefone: "(31) 3333-3333",
      },
      {
        razao_social_cliente: "PowerSolutions LTDA",
        CNPJ: "12345678000194",
        inscricao_estadual: "1234567894",
        endereco: "Estrada das Energias, 150",
        bairro: "Energia",
        CEP: "45678000",
        municipio: "PowerCity",
        UF: "PC",
        telefone: "(41) 4444-4444",
      },
      {
        razao_social_cliente: "DataSystems Ltda",
        CNPJ: "12345678000195",
        inscricao_estadual: "1234567895",
        endereco: "Alameda Dados, 200",
        bairro: "Tecnologia",
        CEP: "56789000",
        municipio: "DataVille",
        UF: "DV",
        telefone: "(51) 5555-5555",
      },
      {
        razao_social_cliente: "InfoTech Solutions",
        CNPJ: "12345678000196",
        inscricao_estadual: "1234567896",
        endereco: "Rua Tecnologia, 500",
        bairro: "Inovações",
        CEP: "67891000",
        municipio: "InfoTown",
        UF: "IT",
        telefone: "(61) 6666-6666",
      },
      {
        razao_social_cliente: "CompTec Comércio",
        CNPJ: "12345678000197",
        inscricao_estadual: "1234567897",
        endereco: "Av. da Tecnologia, 120",
        bairro: "Comercial",
        CEP: "78912000",
        municipio: "CompCity",
        UF: "CC",
        telefone: "(71) 7777-7777",
      },
      {
        razao_social_cliente: "MegaElectro SA",
        CNPJ: "12345678000198",
        inscricao_estadual: "1234567898",
        endereco: "Estrada Eletrônica, 45",
        bairro: "Eletrônica",
        CEP: "89123000",
        municipio: "ElectroVille",
        UF: "EV",
        telefone: "(81) 8888-8888",
      },
      {
        razao_social_cliente: "SmartDevices Ltda",
        CNPJ: "12345678000199",
        inscricao_estadual: "1234567899",
        endereco: "Rua Inovação, 300",
        bairro: "Industrial",
        CEP: "91234000",
        municipio: "DeviceCity",
        UF: "DC",
        telefone: "(91) 9999-9999",
      },
      {
        razao_social_cliente: "Eletronic Corp",
        CNPJ: "12345678000200",
        inscricao_estadual: "1234567800",
        endereco: "Av. Eletrônica, 100",
        bairro: "Corporativo",
        CEP: "10111200",
        municipio: "EletronicCity",
        UF: "EC",
        telefone: "(71) 1234-5678",
      },
      {
        razao_social_cliente: "Tech Innovators LTDA",
        CNPJ: "98765432000100",
        inscricao_estadual: "9988776655",
        endereco: "Rua da Tecnologia, 250",
        bairro: "Inovação",
        CEP: "22033000",
        municipio: "InnovaCity",
        UF: "IC",
        telefone: "(11) 9876-5432",
      },
      {
        razao_social_cliente: "Futuro Digital S/A",
        CNPJ: "33445566000211",
        inscricao_estadual: "6677889900",
        endereco: "Av. do Futuro, 75",
        bairro: "Digital",
        CEP: "33445012",
        municipio: "FuturoVille",
        UF: "FD",
        telefone: "(21) 4567-8901",
      },
      {
        razao_social_cliente: "Global Solutions ME",
        CNPJ: "55667788000322",
        inscricao_estadual: "5566778899",
        endereco: "Av. Global, 44",
        bairro: "Central",
        CEP: "44332211",
        municipio: "GlobalTown",
        UF: "GT",
        telefone: "(48) 1234-5678",
      },
      {
        razao_social_cliente: "Prime Network LTDA",
        CNPJ: "66778899000433",
        inscricao_estadual: "1122334455",
        endereco: "Rua Primeira, 99",
        bairro: "Rede Nova",
        CEP: "55443322",
        municipio: "PrimeCity",
        UF: "PN",
        telefone: "(51) 9876-1234",
      },
      {
        razao_social_cliente: "Nova Conexão Comércio S/A",
        CNPJ: "77889900111244",
        inscricao_estadual: "3344556677",
        endereco: "Av. Conexão, 12",
        bairro: "Interligado",
        CEP: "66554433",
        municipio: "NovaConexãoVille",
        UF: "NC",
        telefone: "(85) 2345-6789",
      },
      {
        razao_social_cliente: "IntegraTech Sistemas LTDA",
        CNPJ: "88990011222355",
        inscricao_estadual: "9988776655",
        endereco: "Rua da Integração, 200",
        bairro: "Integração",
        CEP: "77665544",
        municipio: "IntegraCity",
        UF: "IT",
        telefone: "(61) 8765-4321",
      },
      {
        razao_social_cliente: "Digital Horizons ME",
        CNPJ: "99001122334466",
        inscricao_estadual: "1122337788",
        endereco: "Av. Horizonte, 88",
        bairro: "DigitalCity",
        CEP: "88776655",
        municipio: "HorizonteDigital",
        UF: "DH",
        telefone: "(71) 3456-7890",
      },
      {
        razao_social_cliente: "Soluções Inteligentes LTDA",
        CNPJ: "00112233445577",
        inscricao_estadual: "4455669900",
        endereco: "Rua da Solução, 55",
        bairro: "TechNova",
        CEP: "99887700",
        municipio: "SoluCity",
        UF: "SI",
        telefone: "(83) 5678-1234",
      },
      {
        razao_social_cliente: "InovaCorp LTDA",
        CNPJ: "11223344556688",
        inscricao_estadual: "5566771122",
        endereco: "Av. da Inovação, 303",
        bairro: "InovaBairro",
        CEP: "11223344",
        municipio: "InovaCorpCity",
        UF: "IC",
        telefone: "(91) 6789-1234",
      },
      {
        razao_social_cliente: "Tech Global LTDA",
        CNPJ: "22334455667799",
        inscricao_estadual: "6677882211",
        endereco: "Rua Global, 500",
        bairro: "Mundo Tech",
        CEP: "33445566",
        municipio: "GlobalTechVille",
        UF: "TG",
        telefone: "(31) 7890-4567",
      },
    ],
  });

  // Populando a tabela Fornecedor
  await prisma.fornecedor.createMany({
    data: [
      {
        razao_social_fornecedor: "CompDistribuidora Ltda",
        CNPJ: "12345678000201",
        inscricao_estadual: "2234567891",
        endereco: "Av. Central, 456",
        bairro: "Logística",
        CEP: "10203000",
        municipio: "DistribuVille",
        UF: "DV",
        telefone: "(11) 2134-5678",
      },
      {
        razao_social_fornecedor: "Eletrônica Pro",
        CNPJ: "12345678000202",
        inscricao_estadual: "2234567892",
        endereco: "Rua da Indústria, 89",
        bairro: "Tecnologia",
        CEP: "11213000",
        municipio: "TecnoCenter",
        UF: "TC",
        telefone: "(21) 2345-6789",
      },
      {
        razao_social_fornecedor: "TechSupplies Inc.",
        CNPJ: "12345678000203",
        inscricao_estadual: "2234567893",
        endereco: "Rua Tech, 321",
        bairro: "Fornecedores",
        CEP: "21234000",
        municipio: "SupplyTown",
        UF: "ST",
        telefone: "(31) 3456-7890",
      },
      {
        razao_social_fornecedor: "MegaComponentes",
        CNPJ: "12345678000204",
        inscricao_estadual: "2234567894",
        endereco: "Estrada dos Eletrônicos, 12",
        bairro: "Componentes",
        CEP: "32145000",
        municipio: "CompCity",
        UF: "CC",
        telefone: "(41) 4567-8901",
      },
      {
        razao_social_fornecedor: "ElectroHub",
        CNPJ: "12345678000205",
        inscricao_estadual: "2234567895",
        endereco: "Alameda Eletrônica, 123",
        bairro: "Eletrônicos",
        CEP: "43256000",
        municipio: "HubCity",
        UF: "HC",
        telefone: "(51) 5678-9012",
      },
      {
        razao_social_fornecedor: "Distribuição Global",
        CNPJ: "12345678000206",
        inscricao_estadual: "2234567896",
        endereco: "Av. Logística, 456",
        bairro: "Logística",
        CEP: "54367000",
        municipio: "GlobalDistrib",
        UF: "GD",
        telefone: "(61) 6789-0123",
      },
      {
        razao_social_fornecedor: "InovaCom",
        CNPJ: "12345678000207",
        inscricao_estadual: "2234567897",
        endereco: "Rua Inovação, 98",
        bairro: "Inovações",
        CEP: "65478000",
        municipio: "InovaCity",
        UF: "IC",
        telefone: "(71) 7890-1234",
      },
      {
        razao_social_fornecedor: "Eletronix Parts",
        CNPJ: "12345678000208",
        inscricao_estadual: "2234567898",
        endereco: "Estrada da Eletrônica, 67",
        bairro: "Peças",
        CEP: "76589000",
        municipio: "PartsTown",
        UF: "PT",
        telefone: "(81) 8901-2345",
      },
      {
        razao_social_fornecedor: "TecnoDistribuição",
        CNPJ: "12345678000209",
        inscricao_estadual: "2234567899",
        endereco: "Rua Central, 11",
        bairro: "Distribuição",
        CEP: "87690000",
        municipio: "TecnoDistrib",
        UF: "TD",
        telefone: "(91) 9012-3456",
      },
      {
        razao_social_fornecedor: "Circuitos S/A",
        CNPJ: "12345678000210",
        inscricao_estadual: "2234567810",
        endereco: "Av. dos Circuitos, 78",
        bairro: "Circuitos",
        CEP: "98701000",
        municipio: "CircuitVille",
        UF: "CV",
        telefone: "(81) 3456-7890",
      },
      {
        razao_social_fornecedor: "Tecnologia Avançada LTDA",
        CNPJ: "98765432000111",
        inscricao_estadual: "1122334455",
        endereco: "Rua da Inovação, 12",
        bairro: "Tecnópolis",
        CEP: "88010001",
        municipio: "TechCity",
        UF: "TC",
        telefone: "(48) 1234-5678",
      },
      {
        razao_social_fornecedor: "Eletrônicos Brasil S/A",
        CNPJ: "33445566000222",
        inscricao_estadual: "5566778899",
        endereco: "Av. das Indústrias, 55",
        bairro: "Industrial",
        CEP: "76543210",
        municipio: "Industriópolis",
        UF: "IN",
        telefone: "(11) 9876-5432",
      },
      {
        razao_social_fornecedor: "Alpha Sistemas LTDA",
        CNPJ: "44556677000333",
        inscricao_estadual: "9988776655",
        endereco: "Rua Alpha Beta, 89",
        bairro: "Centro",
        CEP: "45678012",
        municipio: "Alphaville",
        UF: "AL",
        telefone: "(21) 3456-7890",
      },
      {
        razao_social_fornecedor: "Beta Solutions ME",
        CNPJ: "55667788000444",
        inscricao_estadual: "7766554433",
        endereco: "Av. Beta Gamma, 123",
        bairro: "Solutec",
        CEP: "98760045",
        municipio: "BetaVille",
        UF: "BV",
        telefone: "(51) 2345-6789",
      },
      {
        razao_social_fornecedor: "Gamma Importações LTDA",
        CNPJ: "66778899000555",
        inscricao_estadual: "3344556677",
        endereco: "Rua Gamma Delta, 77",
        bairro: "ImportCenter",
        CEP: "12345067",
        municipio: "GammaCity",
        UF: "GC",
        telefone: "(71) 4567-8901",
      },
      {
        razao_social_fornecedor: "Delta Comércio LTDA",
        CNPJ: "77889900111233",
        inscricao_estadual: "2211334455",
        endereco: "Av. Delta Epsilon, 101",
        bairro: "Comercial",
        CEP: "65432001",
        municipio: "DeltaVille",
        UF: "DV",
        telefone: "(31) 8765-4321",
      },
      {
        razao_social_fornecedor: "Omega Componentes S/A",
        CNPJ: "88990011222334",
        inscricao_estadual: "5566332211",
        endereco: "Rua Omega Zeta, 34",
        bairro: "Componentes",
        CEP: "34567012",
        municipio: "OmegaVille",
        UF: "OV",
        telefone: "(91) 9876-6543",
      },
      {
        razao_social_fornecedor: "Fabricação Global ME",
        CNPJ: "99001122334455",
        inscricao_estadual: "1122335544",
        endereco: "Av. Global, 55",
        bairro: "Fábrica Nova",
        CEP: "22334001",
        municipio: "GlobalCity",
        UF: "GC",
        telefone: "(61) 2345-9876",
      },
      {
        razao_social_fornecedor: "Redes Conectadas LTDA",
        CNPJ: "00112233445566",
        inscricao_estadual: "7788990011",
        endereco: "Rua Conexão, 87",
        bairro: "InterConex",
        CEP: "56478045",
        municipio: "NetCity",
        UF: "NC",
        telefone: "(83) 1234-8765",
      },
      {
        razao_social_fornecedor: "Suprimentos Digitais S/A",
        CNPJ: "11223344556677",
        inscricao_estadual: "4455667788",
        endereco: "Av. Digital, 112",
        bairro: "TechSupply",
        CEP: "33445023",
        municipio: "Digitópolis",
        UF: "DP",
        telefone: "(85) 6789-1234",
      },
    ],
  });

  // Populando a tabela Projeto
  await prisma.projeto.createMany({
    data: [
      {
        nome_projeto: "Sistema de Monitoramento",
        responsavel_tecnico: "João da Silva",
        gerente_projeto: "Ana Clara",
        cliente_id: 1,
      },
      {
        nome_projeto: "Automação Residencial",
        responsavel_tecnico: "Marcos Pereira",
        gerente_projeto: "Carlos Lima",
        cliente_id: 2,
      },
      {
        nome_projeto: "Rede de Distribuição",
        responsavel_tecnico: "Luciana Almeida",
        gerente_projeto: "Pedro Fonseca",
        cliente_id: 3,
      },
      {
        nome_projeto: "Plataforma de E-commerce",
        responsavel_tecnico: "Fernanda Torres",
        gerente_projeto: "Gabriel Santos",
        cliente_id: 4,
      },
      {
        nome_projeto: "Sistema de Segurança",
        responsavel_tecnico: "Juliana Araújo",
        gerente_projeto: "Rafael Costa",
        cliente_id: 5,
      },
      {
        nome_projeto: "Gerenciamento de Estoque",
        responsavel_tecnico: "Luis Martins",
        gerente_projeto: "Mariana Gomes",
        cliente_id: 6,
      },
      {
        nome_projeto: "Controle de Acesso",
        responsavel_tecnico: "Thiago Ramos",
        gerente_projeto: "Lívia Nunes",
        cliente_id: 7,
      },
      {
        nome_projeto: "Sistema de Vendas",
        responsavel_tecnico: "Carla Souza",
        gerente_projeto: "Ricardo Lima",
        cliente_id: 8,
      },
      {
        nome_projeto: "Aplicativo Mobile",
        responsavel_tecnico: "Bruno Marques",
        gerente_projeto: "Sofia Mendes",
        cliente_id: 9,
      },
      {
        nome_projeto: "Integração de Sistemas",
        responsavel_tecnico: "Paula Oliveira",
        gerente_projeto: "André Silva",
        cliente_id: 10,
      },
      {
        nome_projeto: "Plataforma de Gestão Empresarial",
        responsavel_tecnico: "Carlos Alberto",
        gerente_projeto: "Mariana Lopes",
        cliente_id: 11,
      },
      {
        nome_projeto: "Sistema de Automação Residencial",
        responsavel_tecnico: "Lucas Pereira",
        gerente_projeto: "Fernanda Souza",
        cliente_id: 12,
      },
      {
        nome_projeto: "Aplicativo de Delivery",
        responsavel_tecnico: "Rafael Mendes",
        gerente_projeto: "Camila Torres",
        cliente_id: 13,
      },
      {
        nome_projeto: "Sistema de Controle de Estoque",
        responsavel_tecnico: "Paulo Henrique",
        gerente_projeto: "Larissa Silva",
        cliente_id: 14,
      },
      {
        nome_projeto: "Portal de Compras Online",
        responsavel_tecnico: "Gabriel Martins",
        gerente_projeto: "Isabela Costa",
        cliente_id: 15,
      },
      {
        nome_projeto: "Sistema de Monitoramento Ambiental",
        responsavel_tecnico: "Ricardo Santos",
        gerente_projeto: "Juliana Almeida",
        cliente_id: 16,
      },
      {
        nome_projeto: "Aplicativo de Saúde e Bem-estar",
        responsavel_tecnico: "Fernando Lima",
        gerente_projeto: "Patrícia Carvalho",
        cliente_id: 17,
      },
      {
        nome_projeto: "Sistema de Gerenciamento Escolar",
        responsavel_tecnico: "Thiago Oliveira",
        gerente_projeto: "Renata Barbosa",
        cliente_id: 18,
      },
      {
        nome_projeto: "Plataforma de E-learning",
        responsavel_tecnico: "André Rocha",
        gerente_projeto: "Simone Ferreira",
        cliente_id: 19,
      },
      {
        nome_projeto: "Sistema de IoT Industrial",
        responsavel_tecnico: "Roberto Campos",
        gerente_projeto: "Vanessa Lima",
        cliente_id: 20,
      },
    ],
  });

  // Populando a tabela Adicionais
  await prisma.adicionais.createMany({
    data: [
      {
        observacoes: "Entrega urgente, prioridade máxima",
      },
      {
        observacoes: "Embalagem especial requerida",
      },
      {
        observacoes: "Fatura com dados fiscais completos",
      },
      {
        observacoes: "Necessário certificado de garantia",
      },
      {
        observacoes: "Produto frágil, manuseio cuidadoso",
      },
      {
        observacoes: "Documentação técnica em inglês",
      },
      {
        observacoes: "Entrega agendada para manhã",
      },
      {
        observacoes: "Nota fiscal em 2 vias",
      },
      {
        observacoes: "Necessário laudo de qualidade",
      },
      {
        observacoes: "Embalagem neutra sem identificação",
      },
    ],
  });

  // Populando a tabela Compra
  await prisma.compra.createMany({
    data: [
      {
        data_compra: new Date("2024-01-15"),
        data_emissao: new Date("2024-01-16"),
        data_envio: new Date("2024-01-20"),
        valor_total: 1200.5,
        xml_url: "",
        produto_id: 1,
        projeto_id: 1,
        fornecedor_id: 1,
        cliente_id: 1,
        adicionais_id: 1,
      },
      {
        data_compra: new Date("2024-02-10"),
        data_emissao: new Date("2024-02-11"),
        data_envio: new Date("2024-02-15"),
        xml_url: "",
        valor_total: 3400.75,
        produto_id: 2,
        projeto_id: 2,
        fornecedor_id: 2,
        cliente_id: 2,
        adicionais_id: 2,
      },
      {
        data_compra: new Date("2024-03-05"),
        data_emissao: new Date("2024-03-06"),
        data_envio: new Date("2024-03-09"),
        valor_total: 2100.2,
        xml_url: "",
        produto_id: 3,
        projeto_id: 3,
        fornecedor_id: 3,
        cliente_id: 3,
        adicionais_id: 3,
      },
      {
        data_compra: new Date("2024-04-01"),
        data_emissao: new Date("2024-04-02"),
        data_envio: new Date("2024-04-07"),
        valor_total: 5600.0,
        xml_url: "",
        produto_id: 4,
        projeto_id: 4,
        fornecedor_id: 4,
        cliente_id: 4,
        adicionais_id: 4,
      },
      {
        data_compra: new Date("2024-04-20"),
        data_emissao: new Date("2024-04-21"),
        data_envio: new Date("2024-04-25"),
        valor_total: 890.3,
        xml_url: "",
        produto_id: 5,
        projeto_id: 5,
        fornecedor_id: 5,
        cliente_id: 5,
        adicionais_id: 5,
      },
      {
        data_compra: new Date("2024-05-10"),
        data_emissao: new Date("2024-05-11"),
        data_envio: new Date("2024-05-14"),
        valor_total: 2750.0,
        xml_url: "",
        produto_id: 6,
        projeto_id: 6,
        fornecedor_id: 6,
        cliente_id: 6,
        adicionais_id: 6,
      },
      {
        data_compra: new Date("2024-06-01"),
        data_emissao: new Date("2024-06-02"),
        data_envio: new Date("2024-06-05"),
        valor_total: 1345.7,
        xml_url: "",
        produto_id: 7,
        projeto_id: 7,
        fornecedor_id: 7,
        cliente_id: 7,
        adicionais_id: 7,
      },
      {
        data_compra: new Date("2024-06-15"),
        data_emissao: new Date("2024-06-16"),
        data_envio: new Date("2024-06-20"),
        valor_total: 6500.0,
        xml_url: "",
        produto_id: 8,
        projeto_id: 8,
        fornecedor_id: 8,
        cliente_id: 8,
        adicionais_id: 8,
      },
      {
        data_compra: new Date("2024-07-05"),
        data_emissao: new Date("2024-07-06"),
        data_envio: new Date("2024-07-10"),
        valor_total: 300.25,
        xml_url: "",
        produto_id: 9,
        projeto_id: 9,
        fornecedor_id: 9,
        cliente_id: 9,
        adicionais_id: 9,
      },
      {
        data_compra: new Date("2024-08-01"),
        data_emissao: new Date("2024-08-02"),
        data_envio: new Date("2024-08-06"),
        valor_total: 980.6,
        xml_url: "",
        produto_id: 10,
        projeto_id: 10,
        fornecedor_id: 10,
        cliente_id: 10,
        adicionais_id: 10,
      },
      {
        data_compra: new Date("2024-02-10"),
        data_emissao: new Date("2024-02-11"),
        data_envio: new Date("2024-02-15"),
        valor_total: 950.75,
        xml_url: "",
        produto_id: 11,
        projeto_id: 11,
        fornecedor_id: 11,
        cliente_id: 11,
      },
      {
        data_compra: new Date("2024-03-05"),
        data_emissao: new Date("2024-03-06"),
        data_envio: new Date("2024-03-10"),
        xml_url: "",
        valor_total: 2400.99,
        produto_id: 12,
        projeto_id: 12,
        fornecedor_id: 12,
        cliente_id: 12,
      },
      {
        data_compra: new Date("2024-04-01"),
        data_emissao: new Date("2024-04-02"),
        data_envio: new Date("2024-04-06"),
        valor_total: 560.0,
        xml_url: "",
        produto_id: 13,
        projeto_id: 13,
        fornecedor_id: 13,
        cliente_id: 13,
      },
      {
        data_compra: new Date("2024-05-12"),
        data_emissao: new Date("2024-05-13"),
        data_envio: new Date("2024-05-18"),
        xml_url: "",
        valor_total: 3000.25,
        produto_id: 14,
        projeto_id: 14,
        fornecedor_id: 14,
        cliente_id: 14,
      },
      {
        data_compra: new Date("2024-06-20"),
        data_emissao: new Date("2024-06-21"),
        data_envio: new Date("2024-06-25"),
        xml_url: "",
        valor_total: 1500.49,
        produto_id: 15,
        projeto_id: 15,
        fornecedor_id: 15,
        cliente_id: 15,
      },
      {
        data_compra: new Date("2024-07-08"),
        data_emissao: new Date("2024-07-09"),
        data_envio: new Date("2024-07-14"),
        valor_total: 780.0,
        xml_url: "",
        produto_id: 16,
        projeto_id: 16,
        fornecedor_id: 16,
        cliente_id: 16,
      },
      {
        data_compra: new Date("2024-08-22"),
        data_emissao: new Date("2024-08-23"),
        data_envio: new Date("2024-08-28"),
        valor_total: 980.75,
        xml_url: "",
        produto_id: 17,
        projeto_id: 17,
        fornecedor_id: 17,
        cliente_id: 17,
      },
      {
        data_compra: new Date("2024-09-10"),
        data_emissao: new Date("2024-09-11"),
        data_envio: new Date("2024-09-15"),
        valor_total: 3200.0,
        xml_url: "",
        produto_id: 18,
        projeto_id: 18,
        fornecedor_id: 18,
        cliente_id: 18,
      },
      {
        data_compra: new Date("2024-10-05"),
        data_emissao: new Date("2024-10-06"),
        data_envio: new Date("2024-10-11"),
        xml_url: "",
        valor_total: 1120.35,
        produto_id: 19,
        projeto_id: 19,
        fornecedor_id: 19,
        cliente_id: 19,
      },
      {
        data_compra: new Date("2024-11-15"),
        data_emissao: new Date("2024-11-16"),
        data_envio: new Date("2024-11-20"),
        xml_url: "",
        valor_total: 4450.89,
        produto_id: 20,
        projeto_id: 20,
        fornecedor_id: 20,
        cliente_id: 20,
      },
    ],
  });

  console.log("Seed concluído com sucesso!");
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
